"use client";

import Link from "next/link";
import { Button } from "../../../../components/ui/button";
import { Skeleton } from "../../../../components/ui/skeleton";
import { useQuery } from "@tanstack/react-query";
import { api } from "../../../../lib/api";
import { useLanguageStore } from "../../../../stores/language-store";
import { translations } from "../../../../lib/translations";

type MarketDetailPageProps = {
  params: { id: string };
};

export default function MarketDetailPage({ params }: MarketDetailPageProps) {
  const { currentLanguage } = useLanguageStore();
  const t = translations[currentLanguage] || translations["en"];

  // 获取市场详情
  const { data: market, isLoading } = useQuery({
    queryKey: ["market", params.id],
    queryFn: () => api.getMarket(params.id),
  });

  // 获取 AI 分析建议
  const { data: aiAnalysis, isLoading: isAiLoading } = useQuery({
    queryKey: ["aiAnalysis", params.id, currentLanguage],
    queryFn: () => api.getAiAnalysis(params.id, currentLanguage),
    enabled: !!market, // 只有市场数据加载后才请求 AI 分析
  });

  return (
    <div className="relative overflow-hidden px-6 pb-24 pt-10 md:px-12 lg:px-20">
      <div className="mb-6 text-sm text-white/50">
        <Link href="/market" className="hover:text-white">
          ← {t.marketDetail.backToMarket}
        </Link>
      </div>

      <div className="glass rounded-3xl p-8">
        <p className="text-xs uppercase tracking-[0.2em] text-white/40">
          {isLoading ? "Loading..." : market?.status}
        </p>
        <h1 className="mt-3 text-3xl font-semibold">
          {isLoading ? <Skeleton className="h-8 w-64" /> : market?.title}
        </h1>
        <p className="mt-2 text-sm text-white/60">
          {t.marketDetail.aiSignal}: {isAiLoading ? "Analyzing..." : "High Probability"}
        </p>

        <div className="mt-6 grid gap-4 md:grid-cols-3">
          <div className="rounded-2xl border border-white/10 p-4">
            <p className="text-xs text-white/40">{t.marketDetail.liquidity}</p>
            <p className="mt-2 text-xl font-semibold">
              {isLoading ? <Skeleton className="h-6 w-20" /> : `$${market?.poolSize?.toLocaleString()}`}
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 p-4">
            <p className="text-xs text-white/40">{t.marketDetail.participants}</p>
            <p className="mt-2 text-xl font-semibold">
              {isLoading ? <Skeleton className="h-6 w-12" /> : "1,240"}
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 p-4">
            <p className="text-xs text-white/40">{t.marketDetail.aiScore}</p>
            <p className="mt-2 text-xl font-semibold">
              {isAiLoading ? <Skeleton className="h-6 w-12" /> : ((aiAnalysis?.confidence ?? 0) * 100).toFixed(1)}
            </p>
          </div>
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_280px]">
          <div className="space-y-4">
            <div className="rounded-2xl border border-white/10 p-4 text-sm text-white/70">
              <p className="text-xs uppercase tracking-[0.2em] text-white/40">{t.marketDetail.oddsTrend}</p>
              <div className="mt-3 space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-4/5" />
                <Skeleton className="h-4 w-2/3" />
              </div>
            </div>
            <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-neon-purple/5 p-4 text-sm text-white/70">
              <div className="absolute -right-4 -top-4 text-4xl opacity-10">🤖</div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-neon-purple-bright">
                {t.marketDetail.aiView}
              </p>
              <p className="mt-3 italic leading-relaxed">
                {isAiLoading ? (
                  <span className="flex flex-col gap-2">
                    <Skeleton className="h-3 w-full" />
                    <Skeleton className="h-3 w-5/6" />
                  </span>
                ) : (
                  aiAnalysis?.analysis || t.marketDetail.aiViewContent
                )}
              </p>
              {!isAiLoading && (
                <div className="mt-4 flex items-center gap-2 text-[10px] font-bold uppercase text-white/30">
                  <span className="h-1.5 w-1.5 rounded-full bg-neon-purple animate-pulse" />
                  Generated by Superoctop AI Analyst v1.0
                </div>
              )}
            </div>
          </div>
          <div className="rounded-2xl border border-white/10 p-4">
            <p className="text-xs uppercase tracking-[0.2em] text-white/40">{t.marketDetail.quickBet}</p>
            <div className="mt-4 space-y-3">
              <Button variant="solid" className="w-full">
                {t.marketDetail.betYes}
              </Button>
              <Button variant="outline" className="w-full">
                {t.marketDetail.betNo}
              </Button>
              <Button variant="ghost" className="w-full">
                {t.marketDetail.setStopLoss}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

